# Options for analysis running.
run:
  # vendor$, third_party$, testdata$, examples$, Godeps$, builtin$
  skip-dirs-use-default: true
  skip-dirs:
    - dist/
    - pkg/
  skip-files:
    - ".*\\.pb\\.go$"
# output configuration options
output:
  format: colored-line-number
# Refer to https://golangci-lint.run/usage/linters
linters:
  disable-all: true
  enable:
    - goimports
    - gofmt
    - misspell
    - govet
    - ineffassign
    - staticcheck
issues:
  exclude-use-default: true