name: main

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ "*" ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.21

    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install Dependencies
      run: make api_dep_install

    - name: Install Protoc
      uses: arduino/setup-protoc@v1

    - name: Generate API
      run: make api_gen
  
    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
        args: --verbose --timeout 50m

  docker:
    runs-on: ubuntu-latest
    needs: lint
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/amd64,linux/arm64
        push: true
        tags: letscrum/letscrum:latest

    deploy:
      runs-on: ubuntu-latest
      needs: docker
      steps:
        - name: Deploy to Server
          uses: appleboy/ssh-action@master
          with:
              host: ${{ secrets.DEMO_SERVER_IP }}
              port: ${{ secrets.DEMO_SERVER_PORT }}
              username: ${{ secrets.DEMO_SERVER_USERNAME }}
              password: ${{ secrets.DEMO_SERVER_PASSWORD }}
              script: |
                docker stop letscrum
                docker rm letscrum
                docker image rm letscrum/letscrum:latest
                docker pull letscrum/letscrum:latest
                docker run -d --name letscrum -v /etc/letscrum/config.yaml:/etc/letscrum/config.yaml -p 8081:8081 -p 9091:9091 letscrum/letscrum:latest
