name: Pre-check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ "*" ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.21

    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install Dependencies
      run: make api_dep_install

    - name: Install Protoc
      uses: arduino/setup-protoc@v1

    - name: Generate API
      run: make api_gen
  
    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
        args: --verbose --timeout 50m

  docker:
    runs-on: ubuntu-latest
    needs: lint
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/amd64,linux/arm64
        push: true
        tags: letscrum/letscrum:latest

